### ISSUE TITLE
version bumping

### ISSUE THREAD

**Issue by rismoney** [jumanjihouse/docker-aws#231]
perhaps using a lamba function that calls the circleci api to trigger a nightly build can move to a more optimistic versioning approach with less maintenance.

recently came across this-
https://github.com/tsub/circleci-build-trigger

**Comment by jumanjiman** [comment]
thanks for the link and suggestion.

i've thought about using https://github.com/sloria/pypi-cli to watch the version on pypi and trigger a build-and-publish when that version changes. The link you provided could certainly help with the scheduling.
